### ISSUE TITLE
Use of ../ in listsNM.def fails for some classloaders

### ISSUE THREAD

**Issue by cuspycode** [GateNLP/gateplugin-ANNIE#10]
I recently upgraded from GATE 8.1 to GATE 8.6, and ANNIE won't load now when I run from a Spring Boot fat jar. It turns out that the classloader doesn't resolve the path `../gazetteer/org_ending.lst` in the file `/resources/othomatcher/listsNM.def` because the Spring Boot classloader doesn't interpret `..` in the path like the default JDK classloader does.

Changing the line to `/resources/gazetteer/org_ending.lst:cdg` fixes it for me.

**Comment by greenwoodma** [comment]
GATE Plugins shouldn't be included inside a jar file as that would put them on the wrong classloader which could cause issues with class definitions. While it might have worked in 8.1 that probably was more by luck than anything else and may have failed in interesting ways depending on which other plugins were loaded/included in the JAR file.
