### ISSUE TITLE
Local maven cache referenced when saving pre-made ANNIE

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-ANNIE#16]
Using GATE 9.0 on linux, java version 8.

I load the pre-made ANNIE pipeline, than save it as an xgapp file. 

The saved file contains the following:
```
        <entry>
          <string>gate.app.MetadataURL</string>
          <gate.util.persistence.PersistenceManager-URLHolder>
            <urlString>jar:file:/home/johann/.m2/repository/uk/ac/gate/plugins/annie/9.0/annie-9.0.jar!/resources/.annie-defaults-metadata/metadata.xml</urlString>
          </gate.util.persistence.PersistenceManager-URLHolder>
        </entry>
```

**Comment by greenwoodma** [comment]
hmmmm, my guess, and I'd need to check, is that the feature is just stored as a URL and not a ResourceReference. In the xgapp it's probably a relative URL to the metadata file, so when you save the xgapp you correctly get a URL into the jar file in your maven cache. Given it's a URL in the feature value this is the correct behaviour, even though it looks a bit nasty.

We should look at using ResourceReference for this globally (which is a change to gate-core to use that correctly in the metadata viewer) to make this look better.

**Comment by johann-petrak** [comment]
I think it would be important to make this a ResourceReference as any saved/modified gapp from a prepared pipeline would not work if moved to a different user/machine etc. 
I guess one would expect that a saved annie.xgapp file should work anywhere.

**Comment by ianroberts** [comment]
Note that the only thing that this breaks is the info tab, which most people don't even realise is there.

**Comment by johann-petrak** [comment]
Ah i guess I was too worried that it would show an exception, but apparently it does not even do that!

**Comment by greenwoodma** [comment]
Turns out that the metadata viewer in the GUI already had code to behave differently for `URL` and `ResourceReference` versions of the feature so the fix was to manually change the persistence type in the xgapp from `URLHolder` to `RRPersistence` and the value holder from `urlString` to `uriString`. We should probably check other apps for the same problem.
