### ISSUE TITLE
Hardcoded Encoding in Gazetteers

### ISSUE THREAD

**Issue by MarianaFerrDias** [GateNLP/gateplugin-ANNIE#19]
For all the Gazetteer resources that extend the AbstractGazetteer class, the encoding is hardcoded to "UTF-8", while in the GUI the encoding is requested as an initialisation parameter.

https://github.com/GateNLP/gateplugin-ANNIE/blob/9057ae622f5e5c8ed64cf862b21a0226f1084560/src/main/java/gate/creole/gazetteer/AbstractGazetteer.java#L46

**Comment by greenwoodma** [comment]
That hard coded value for the encoding will always be overwritten when you create an instance of the gazetteer. The setEncoding() method will be called when the instance is created to store the encoding specified by the user (or the default of UTF-8).

**Comment by MarianaFerrDias** [comment]
Oh you're right! However, that setEncoding function is never called. I'm testing a pipeline with Hash Gazetteer encoded in ISO-8859-1 encoding. In the function init() in HashGazetteer.java there needs to be a call to definition.setEnconding(encoding).

**Comment by greenwoodma** [comment]
Oh yes. It looks as if LinearDefinition always uses utf8 via the static ENCODING variable) rather than the using the instance variable set by LinearDefinition.setEncoding() plus that never seems to be called, even in DefaultGazetteer. Definitely looks like a bug.

**Comment by greenwoodma** [comment]
I've now fixed this and it should work properly in version 9.1-SNAPSHOT of the ANNIE plugin. Note that the encoding only applies to the content of the 1*.lst1 files. The `lists.def` file is still assumed to be encoded as UTF-8 -- I think this makes sense and shouldn't break any previous usage.
