### ISSUE TITLE
Ontology-Aware JAPE Transducer

### ISSUE THREAD

**Issue by MarianaFerrDias** [GateNLP/gateplugin-ANNIE#20]
I'm using GATE 9.0 and in the documentation it is mentioned that it is possible to input an ontology parameter for the JAPE grammar, but the tool doesn't give you that option. I was reading the code and noticed that it seems to have been disabled due to past issues with the Ontology plugin.

Is it an easy fix? I wanted to use it for ontology population purposes.

**Comment by greenwoodma** [comment]
You can still pass an ontology to a JAPE Transducer. Note that it's a runtime parameter so is provided when you configure the PR as part of a pipeline and not when you first create it. Also note that it's a hidden param on the ANNIE NE Transducer so you have to create an instance of JAPE Transducer if you want to use that parameter.
