### ISSUE TITLE
`org_context.jape` adds extra space to each feature key

### ISSUE THREAD

**Issue by SomervilleTom** [GateNLP/gateplugin-ANNIE#22]
Each feature added by `'org_context.jape'` has an incorrect key -- each key has an extra trailing space. This breaks tools that attempt to parse the resulting rules.

28 of the 29 `.jape` files in 'src/main/resources/resources/NE' provide a double-quote delimited key as the first argument in each invocation of `feature.put`. There are no leading or trailing spaces for any of those feature keys.

In `org_context.jape`, each of the 30 invocations of `feature.put` has an apparently extraneous space before the trailing double-quote.

For example, the rule for `'orgConj2'` is as follows:

```
Rule: OrgConjOrg2
Priority: 10

(
 {Organization}
 {Token.category == CC}
)
(
 {Unknown.kind == PN}
):org
-->
 {
gate.AnnotationSet org = (gate.AnnotationSet) bindings.get("org");
gate.FeatureMap features = Factory.newFeatureMap();
features.put("rule ", "OrgConjOrg2");
features.put("orgType ", "unknown");
outputAS.add(org.firstNode(), org.lastNode(), "Organization",
features);
outputAS.removeAll(org);
}
```

Note these two apparently incorrect lines:

```
features.put("rule ", "OrgConjOrg2");
features.put("orgType ", "unknown");
```

This adds two features with the following (incorrect) keys:

* '"rule "'
* '"orgType "'

The correct value of these keys is:

* '"rule"'
* '"orgType"'

The trailing space breaks a toolchain my team is creating that uses the annotations created by GATE.

While I'm surprised that this bug is still present after more than two decades of use (at least according to the comment in the file), it is creating a problem for our project -- hence this new issue.

**Comment by greenwoodma** [comment]
Wow, you're right I can't believe that bug has persisted for so long. Thanks for spotting and reporting it.

**Comment by greenwoodma** [comment]
the automated build has now completed as well, so if you are using 9.1-SNAPSHOT of the ANNIE plugin then you should get the corrected version when you re-pull the plugin: you can delete the cached version from your `~/.m2` folder if you need to force that.

**Comment by SomervilleTom** [comment]
Please pardon my ignorance -- I can't figure out how to actually USE this change. I'm not a maven or Java configuration expert.

I run a local version of "gate-core". I run "GATE Developer" from the zipfile that I downloaded. When I start "GATE Developer", I see the following in the command line (an SSH client):

```
[tms@hoyo ~]$ gateDeveloper
Running GATE using Java at /usr/lib/jvm/jre-openjdk/bin/java
/usr/lib/jvm/jre-openjdk/bin/java -Xms200m -Djava.net.useSystemProxies=true -splash:/var/lib/gate/gate-developer-9.0.1/bin/splash.png -jar /var/lib/gate/gate-developer-9.0.1/bin/gateLauncher.jar
Using /home/tms/.gate.xml as user configuration file
Using /home/tms/.gate.session as user session file
CREOLE plugin loaded: creole 
```
While the directory '/home/tms/.gate' exists, there is no file named "/home/tms/.gate.xml" or "/home/tms/.gate.session".

It does contain "logfile.txt", and I can see updates to that.

When "GATE Developer" starts, the "CREOLE Plugin Manager"  lists "ANNIE (9.1)" as the plugin name. When I click the "+" to add a plugin and specify "ANNIE" as the artifact and "9.1-SNAPSHOT" as the version, it complains of an invalid plugin.

How do I specify things the version of the ANNIE plugin that I want to run?

I've pored through the user guide and haven't found anything yet.

**Comment by ianroberts** [comment]
> When "GATE Developer" starts, the "CREOLE Plugin Manager" lists "ANNIE (9.1)" as the plugin name. When I click the "+" to add a plugin and specify "ANNIE" as the artifact and "9.1-SNAPSHOT" as the version, it complains of an invalid plugin.

Apologies, the updated plugin is version `9.2-SNAPSHOT`, not `9.1-SNAPSHOT`.  So in the plugin manager you want

- group: `uk.ac.gate.plugins`
- artifact: `annie` (lower case!)
- version: `9.2-SNAPSHOT`

This will add ANNIE version 9.2-SNAPSHOT to the list, you will need to _untick_ ANNIE 9.1, then apply all, then tick 9.2-SNAPSHOT, then apply all again.

Sadly this will delete any ANNIE 9.1 PRs that you have open, you'll have to re-create them once you've loaded 9.2-SNAPSHOT

**Comment by SomervilleTom** [comment]
AH -- that's very helpful. I'm not worried about recreating things, I'm just trying wrap my head around how all this works. :)

**Comment by ianroberts** [comment]
Yeah, sorry, I guess it's kind of assumed knowledge around the way that Maven dependencies are typically named - what you have to provide in the group/artifact/version fields are the machine-readable Maven "co-ordinates" of the plugin you want to download, but what shows in the list of checkboxes is the human-readable name of the plugin taken from its resolved metadata.  All the standard plugin co-ordinates are lower-case-with-hyphens (`format-json`, `lang-arabic`, `tagger-framework`, etc.) but the names are mixed case names meaningful to a human user ("Format: JSON", "Language: Arabic", "Tagger Framework").

**Comment by SomervilleTom** [comment]
While the "CREOLE Plugin Manager" now allows me to add "ANNIE (9.2-SNAPSHOT)", clicking the "-" button flashes the screen and shows no other apparent change. No rows are deleted, all the check marks remain. It looks as though I need to edit the startup configuration myself somehow.

I apologize for overusing this board, this thread is clearly outside the scope of the specific solved issue. I appreciate your patience.

**Comment by ianroberts** [comment]
The `-` button is for removing a plugin from the list, you don't need to do that.  You've now got ANNIE 9.1 and 9.2-SNAPSHOT both slowing in the list right?  So now you need to

- untick "load now" and "load always" for _all_ versions of ANNIE
- click "apply all" at the bottom
  - you now do not have any ANNIE plugins loaded
- tick "load now" for ANNIE 9.2-SNAPSHOT (and load always if you want)
- click "apply all" again
  - you now have ANNIE 9.2-SNAPSHOT loaded
- click "close"

Now when you load the ANNIE application with the ![ANNIE](https://raw.githubusercontent.com/GateNLP/gate-core/f15c9d3d923fbd7761c0f53fbdc259a62baaed70/src/main/svg/AnnieApplication.svg) button it will use the new version.

**Comment by SomervilleTom** [comment]
It appears to me that the changes made to `org_context.jape` are not being loaded with either "ANNIE (9.2-SNAPSHOT)" or "ANNIE (9.1-SNAPSHOT)". 

I followed the above recipe, made sure that "ANNIE (9.2-SNAPSHOT)" is showing in the plugin manager, checked both "load now" and "load always", and clicked "Appy All". I then closed the plugin manager. Here is the content of the "Message" pane after doing this:

```
GATE 9.0.1 build 5271e02 started at Thu Nov 16 21:36:36 UTC 2023
and using Java 1.8.0_392 Red Hat, Inc. on Linux amd64 4.18.0-477.27.1.el8_8.x86_64.
CREOLE plugin loaded: ANNIE 9.2-SNAPSHOT
```

I then loaded the ANNIE application with the above button. After it loaded, I navigated to and showed the "ANNIE NE Transducer" resource. In the resulting viewer, I selected the "org_context" child of "main".

I did the same for "ANNIE (9.1-SNAPSHOT)", with the same result.

I see no changes in the "feature.put" items -- it appears that the change that solves this issue is not actually being deployed.

**Comment by SomervilleTom** [comment]
There was a stale item in my '~/.m2' directory for 9.2-SNAPSHOT. I removed that, and I now see the new change in the "ANNIE NE Transducer" PR.

Well -- that was fun! I appreciate all the help from each of you, and I apologize for adding so much discussion to this thread.
